### ISSUE TITLE
[BUG] Table of Contents is nested too much

### ISSUE THREAD

**Issue by Jarmos-san** [adityatelange/hugo-PaperMod#624] opened 2021-11-08 21:28 UTC
**Describe the bug**
"Table of Contents" is nested which shouldn't be as such. Screenshot attached below for further reference.

 - Device/Os: Windows 10
 - Type: Desktop
 - Browser and version: Microsoft Edge v95.0.1020.44 (Official build) (64-bit)
 - Hugo Version [ >=0.83.0 expected]: hugo v0.89.0+extended linux/amd64
 - Theme Version [e.g. v4.0, master, or commit-id ]: 3bcafa0be9461124fcd2a09a58799e2fd1e7a505

**Steps to reproduce the behavior:**
1. Create an article with frontmatter key-value pair set to `showtoc: true`.
2. With the Hugo server running, check the generated articles table of contents (ToC).
3. Check the ToC & see how nested it is.

**Expected behavior**:
ToC shouldn't be too nested.

**Screenshots**

![image](https://user-images.githubusercontent.com/31373860/140820898-88964691-7dc0-46c8-8f0c-5603549e7bf0.png)

**Comment by adityatelange** [comment] 2021-11-09 08:33
Hi @Jarmos-san, this seems to be issue on your end. 
Cannot reproduce this issue with already deployed demo.

Check this https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/content/posts/markdown-syntax.md?plain=1 source, which renders as https://adityatelange.github.io/hugo-PaperMod/posts/markdown-syntax/

**Comment by Jarmos-san** [comment] 2021-11-09 09:15
I see, so what should I look at to fix this issue? I don't know anything about Golang and/or Go templates, so a little bit of guidance can be helpful here.

**Comment by adityatelange** [comment] 2021-11-09 11:20
> I see, so what should I look at to fix this issue? I don't know anything about Golang and/or Go templates, so a little bit of guidance can be helpful here.

I cannot suggest anything. Maybe you have overridden any template file in your source. But that is more of a Discussion topic than a Bug.

I'll close this issue as this is not occurring with everyone else using the theme.

**Closed by adityatelange** 2021-11-09 11:20 UTC
Labels: bug
