### ISSUE TITLE
[REQUEST] Add Mastodon Share Button

### ISSUE THREAD

**Issue by retiolus** [adityatelange/hugo-PaperMod#1189] opened 2023-04-17 10:45 UTC

**Comment by mustafaalbazy** [comment] 2023-06-19 16:38
I have added the Mastodon share button in the latest pull request. Until they review it and approve it, you can copy it straightaway on your site/blog if you wish. 

#1240

**Comment by besendorf** [comment] 2023-10-16 11:52
@retiolus the PR is still open but the issue is closed. Could you reopen the issue until the PR is merged?

**Comment by adityatelange** [comment] 2023-11-11 09:38
TL;DR It can't be implemented with ease.

This could not be added as mastodon is a decentralized social media. An instance needs to be chosen 1st then a link can be created to post it. It more difficult to implement a share button that works consistently across all Mastodon instances.

About the PR, it only mentions `mastodon.social` and it will ask you to sign-in in order to share the link instead of choosing the instance. 
![image](https://github.com/adityatelange/hugo-PaperMod/assets/21258296/bef1e219-d281-4305-8407-ac90b92fa63b)

**Closed by adityatelange** 2023-11-11 09:38 UTC
Labels: out-of-scope

**Comment by besendorf** [comment] 2023-11-11 11:43
You could just use this solution: https://aly-ve.github.io/Mastodon-share-button/
It asks the user for their Mastodon Server and optionally saves their server.
