### ISSUE TITLE
[BUG]  failed to render pages: render of "home" failed

### ISSUE THREAD

**Issue by smailzhu** [adityatelange/hugo-PaperMod#1019] opened 2022-08-22 14:40 UTC
**Describe the bug**

 - Device/Os: windows/arm64
 - Type: build
 - Hugo Version [ >=0.83.0 expected]: v0.101
 - Theme Version [e.g. v4.0, master, or commit-id ]: https://github.com/adityatelange/hugo-PaperMod/commit/b906338dc82a48e0fa8c8d4160a09c8b07302472

**Steps to reproduce the behavior:**
while enable `profileMode` and set `imageUrl` set with a online link in config/languages

exec `hugo server -D`

see error

Error: Error building site: failed to render pages: render of "home" failed: "themes\PaperMod\layouts\_default\list.html:4:4": execute of template failed: template: _default/list.html:4:4: executing "main" at <partial "index_profile.html" .>: error calling partial: themes\PaperMod\layouts\partials\index_profile.html:5:29": execute of template failed: template: partials/index_profile.html:5:29: executing "partials/index_profile.html" at <resources.Get>: error calling Get: CreateFile themes\PaperMod\assets\[imageUrl in config]: The filename, directory name, or volume label syntax is incorrect.

**Expected behavior**:

**Screenshots**

**Additional context**

May need to check if the image is a file or something else
https://github.com/adityatelange/hugo-PaperMod/commit/2bb7687a34f3e3af9aff885de67b29216ff0751f

**Comment by adityatelange** [comment] 2022-08-27 14:51
@smailzhu Can you pls share a demo repo where this error is throwing up? It would be really helpful.

**Comment by smailzhu** [comment] 2022-08-28 15:12
Of course!!  It shows in the example site as well.

The steps can show the error are

1. `git clone -b exampleSite git@github.com:adityatelange/hugo-PaperMod.git`
2. `cd hugo-PaperMod/themes`
3. `git clone git@github.com:adityatelange/hugo-PaperMod.git`
4.  `cd ..`
5. `hugo server`


> Error: Error building site: failed to render pages: render of "home" failed: "\hugo-PaperMod\themes\hugo-PaperMod\layouts\_default\list.html:4:4": execute of template failed: template: _default/list.html:4:4: executing "main" at <partial "index_profile.html" .>: error calling partial: "\hugo-PaperMod\themes\hugo-PaperMod\layouts\partials\index_profile.html:5:29": execute of template failed: template: partials/index_profile.html:5:29: executing "partials/index_profile.html" at <resources.Get>: error calling Get: CreateFile \hugo-PaperMod\assets\https:\raw.githubusercontent.com\twitter\twemoji\master\assets\svg\1f317.svg: The filename, directory name, or volume label syntax is incorrect.

**Comment by lguenth** [comment] 2022-08-29 22:06
I've also been trying to build the example site but it's failing with that error.

**Comment by adityatelange** [comment] 2022-08-31 08:35
> Of course!! It shows in the example site as well.
> 
> The steps can show the error are
> 
> 1. `git clone -b exampleSite git@github.com:adityatelange/hugo-PaperMod.git`
> 2. `cd hugo-PaperMod/themes`
> 3. `git clone git@github.com:adityatelange/hugo-PaperMod.git`
> 4. `cd ..`
> 5. `hugo server`
> 
> > Error: Error building site: failed to render pages: render of "home" failed: "\hugo-PaperMod\themes\hugo-PaperMod\layouts_default\list.html:4:4": execute of template failed: template: _default/list.html:4:4: executing "main" at <partial "index_profile.html" .>: error calling partial: "\hugo-PaperMod\themes\hugo-PaperMod\layouts\partials\index_profile.html:5:29": execute of template failed: template: partials/index_profile.html:5:29: executing "partials/index_profile.html" at <resources.Get>: error calling Get: CreateFile \hugo-PaperMod\assets\https:\raw.githubusercontent.com\twitter\twemoji\master\assets\svg\1f317.svg: The filename, directory name, or volume label syntax is incorrect.

Used these steps, but it just worked fine, checkout the below image
![image](https://user-images.githubusercontent.com/21258296/187634456-010a3a6b-6479-4610-b619-f5f3715df26b.png)

**Comment by smailzhu** [comment] 2022-08-31 09:06
> Used these steps, but it just worked fine, checkout the below image

I've tried the same steps on another ubuntu, it works fine as well...
But it broke on my Windows 10

@lguenth may I ask which OS you saw the error shows?

**Comment by lguenth** [comment] 2022-08-31 09:16
I'm sorry, I just tried again and it works. I'm not sure what I did the first time around but I can't reproduce it anymore. For reference, I'm on vanilla Ubuntu 22.04 LTS.

**Comment by smailzhu** [comment] 2022-08-31 09:33
I used the [release from hugo github repository](https://github.com/gohugoio/hugo/releases). and do the same steps.

Maybe there's some configuration issue on my computer. Anyway, thanks for your time.

btw, this is the error screenshot.

![image](https://user-images.githubusercontent.com/9101328/187646168-93a58c8b-6fb0-4f8c-9525-eec9bddad657.png)

**Comment by adityatelange** [comment] 2022-08-31 09:33
> > Used these steps, but it just worked fine, checkout the below image
> 
> I've tried the same steps on another ubuntu, it works fine as well... But it broke on my Windows 10
> 
> @lguenth may I ask which OS you saw the error shows?

True, getting the error with windows build, not sure why though, you might need to ask Hugo devs.

![image](https://user-images.githubusercontent.com/21258296/187647284-05003570-791b-4a77-af16-15a55e19a331.png)

**Comment by smailzhu** [comment] 2022-08-31 09:42
@adityatelange 
I'm wondering if is there a way to check if `.imageUrl` is a local file or internet resource before resizing it.
In the revise in commit https://github.com/adityatelange/hugo-PaperMod/commit/2bb7687a34f3e3af9aff885de67b29216ff0751f

**Comment by adityatelange** [comment] 2022-08-31 10:04
@smailzhu If you read these docs https://gohugo.io/content-management/image-processing/#image-rendering and https://gohugo.io/content-management/image-processing/#image-rendering
They mention `resources.Get and resources.GetRemote return nil if the resource is not found.`

**Comment by adityatelange** [comment] 2022-08-31 10:05
We are using similar code to process cover images as well... this needs a research
https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/partials/cover.html#L7

**Comment by adityatelange** [comment] 2022-09-03 10:38
@smailzhu can you pls check if this is fixed on your end with https://github.com/adityatelange/hugo-PaperMod/commit/ddfea82cc75c93074194490df3805d28f7852248

**Closed** 2022-09-03 10:37 UTC
Labels: bug

**Comment by smailzhu** [comment] 2022-09-03 11:31
it works !! Thanks a lot 😄
