### ISSUE TITLE
[BUG]Display is wrong about highlight

### ISSUE THREAD

**Issue by fissssssh** [adityatelange/hugo-PaperMod#1136] opened 2023-01-17 09:48 UTC
The display is wrong when the line number and the highlighted line are turned on at the same time

**Source**
\```csharp {linenos=table,hl_lines=[6]}
var json = "{\"Name\":\"fissssssh\"}";

// 创建一个键名忽略大小写的字典对象
var dict = new Dictionary<string,string>(StringComparer.InvariantCultureIgnoreCase);

JsonConvert.PopulateObject(json, dict);

// 使用 name 获取 JSON 中的 Name 属性值
var name = dict["name"];
\```

**Screenshots**
![image](https://user-images.githubusercontent.com/29757779/212865307-1dd02b0a-0cd5-4008-869b-66c112db0d37.png)

**Comment by adityatelange** [comment] 2023-01-18 17:49
@fissssssh  Avoid submitting Bug reports without templates. 
Duplicate of #923. Please pull the latest commits.

**Closed by adityatelange** 2023-01-18 17:49 UTC
Labels: bug
