### ISSUE TITLE
cannot override templates

### ISSUE THREAD

**Issue by pixelfabs** [adityatelange/hugo-PaperMod#303] opened 2021-03-12 04:05 UTC
Maybe I'm missing something. I have some pages which have no default layout. About Us for example, I made about-us.md in content and about-us.html in layouts (not papermod/layouts). But no matter what I try or even move around about-us.html, it doesn't change. It keeps using single.html from PaperMod itself. 

What am I missing?

Regards,

Micheal

**Comment by kdkasad** [comment] 2021-03-12 04:14
Have you added the following in `about-us.md`'s front matter?
```yaml
layout: about-us
```

Take a look at the [template lookup order for Hugo](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-regular-pages). There's no reason Hugo would use `layouts/_default/about-us.html` as the template unless you specifically tell it to.

**Comment by pixelfabs** [comment] 2021-03-12 05:34
I did. I went on, and when I place the about-us.html into the actual themes/PaperMod/ dir, then it does work. But that's going to make updating the theme a cumbersome job. 

I had this issue earlier with another theme, but now for the second time I must have done something wrong in the past, perhaps when installing hugo or a misconfiguration somewhere.  But where that could be? 

Anyhow, thank you so much for this amazing theme. I know how hard it can be to produce a fast loading theme.

**Comment by kdkasad** [comment] 2021-03-12 17:59
> I did. I went on, and when I place the about-us.html into the actual themes/PaperMod/ dir, then it does work. But that's going to make updating the theme a cumbersome job.

Weird. I can't seem to reproduce that issue. Here's a tarball of a test site that works fine for me. The **About Us** page should have only a header with the text "*test*".

Try that test site. If it doesn't work, something is probably wrong with your version of Hugo (it may be outdated).

**Comment by adityatelange** [comment] 2021-03-18 11:31
@pixelfabs I can't reproduce your issue, doesn't seem to be an issue at all :eyes: , closing

**Closed by adityatelange** 2021-03-18 11:31 UTC

**Comment by pixelfabs** [comment] 2021-04-12 06:14
Indeed. Invalid. Your files work. As well my files. Not sure why. Thank you so much! (and sorry for late response, been very busy).
