### ISSUE TITLE
[BUG] Search results seem to be duplicated

### ISSUE THREAD

**Issue by eriknelson** [adityatelange/hugo-PaperMod#414] opened 2021-05-21 19:19 UTC
**Describe the bug**

 - Device/Os: [e.g. Android 10]: MacOS Big Sur 11.2.3
 - Type: [e.g. Desktop/Mobile] Desktop
 - Browser and version [e.g. Chrome 86.0]: Firefox 78.10
 - Hugo Version [ >=0.82.0 expected]: v0.83.1
 - Theme Version [e.g. v4.0, master, or commit-id ]: master

I seem to be getting duplicate entries with search hits on my search page, see screenshot.

**EDIT:** This seems to only manifest within a development environment with `hugo server`. Once deployed with netlify, I'm not seeing the issue.

**Steps to reproduce the behavior:**
Enabled search following the Features page of papermod

Added

```
outputs:
  home:
    - HTML
    - RSS
    - JSON
```

Added `content/search.md` with the following contents:

```
---
title: "Search" # in any language you want
layout: "search" # is necessary
# url: "/archive"
# description: "Description for Search"
summary: "search"
---
```

**Expected behavior**:
Single entry results.

**Screenshots**
<img width="820" alt="image" src="https://user-images.githubusercontent.com/410933/119187846-de4d8a00-ba47-11eb-88eb-faae7ffae14e.png">

Happy to work with you to diagnose, please let me know if I can provide any more helpful info.

**Comment by adityatelange** [comment] 2021-06-11 08:17
> **EDIT:** This seems to only manifest within a development environment with `hugo server`. Once deployed with netlify, I'm not seeing the issue.

Yes. Exactly. I am also confused with this actually :sweat_smile:

**Comment by adityatelange** [comment] 2021-06-15 05:33
Found out that the problem is not because of [scripts](https://github.com/adityatelange/hugo-PaperMod/blob/master/assets/js/fastsearch.js) for search and also not because of [index.json](https://github.com/adityatelange/hugo-PaperMod/blob/master/layouts/_default/index.json).

This happens due to the fast-reload template cache in Hugo, in the development environment. The `/index.json` values are duplicated because of this and not because they are not using `uniq`. 
As a result, I don't think there is a fix for this.

**Comment by eriknelson** [comment] 2021-06-15 14:15
@adityatelange would you like to leave this open or I can close as well if this is a CANTFIX?

**Comment by adityatelange** [comment] 2021-06-20 08:26
> @adityatelange would you like to leave this open or I can close as well if this is a CANTFIX?

We can close this, but I _may_ be wrong.

**Closed** 2021-06-21 15:49 UTC
Labels: bug
